spring:
  datasource:
    url: jdbc:h2:mem:cdrdb;DB_CLOSE_DELAY=-1
    driverClassName: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: none
  flyway:
    enabled: true
    locations: classpath:db/migration

rabbitmq:
  host: localhost
  port: 5672
  username: guest
  password: guest

cdr:
  send:
    delay: 10000
