spring.application.name: crm

server:
  port: 8083

spring:


  datasource:
    #    platform: postgres
    url: "jdbc:postgresql://postgres_crm:5432/crm_db"
    username: user
    password: password
    driverClassName: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none

  liquibase:
    enabled: true
    change-log: db/changelog/db.changelog-master.yaml
    default-schema: public


  main:
    allow-bean-definition-overriding: true



hrs:
  service:
    url: "http://hrs:8082"

brt:
  service:
    url: "http://brt:8081"

