spring.application.name: brt

server:
  port: 8081

spring:
  datasource:
    #    platform: postgres
    url: "jdbc:postgresql://postgres_brt:5432/brt_db"
    username: user
    password: password
    driverClassName: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none

  liquibase:
    enabled: true
    change-log: db/changelog/db.changelog-master.yaml
    default-schema: public
  rabbitmq:
    host: localRabbitMQ
    username: user
    password: password
    ports:
      - "5672:5672"
    template:
      exchange: cdr_exchange
      routing-key: cdr_routing_key
      default-receive-queue: cdr_queue
hrs:
  service:
    url: "http://hrs:8082"
